### ISSUE TITLE
Forgot Key

### ISSUE THREAD

**Issue by PowerPress** [fruiz500/PassLok-Privacy#1]
If you forget your key and open passlok and try to backup/reset options or change key you cant because it wants your old key. Make a clear method to remove the old incase its forgotten and you want to start over.

**Comment by fruiz500** [comment]
In version 2.0.02, the method is to Cancel key entry, then go to the Options tab and uncheck "Check Key", then try again. But this is getting simplified in v2.0.03, so that users would be able to use most of the functionality even without entering a Key.
Thanks for the comment!

**Comment by fruiz500** [comment]
As of version 2.1.02, the method to recover from this situation is as follows:
1. Cancel Key entry. PassLok shows the Main tab in limited mode. A message warns the user of this fact.
2. Go to the Options tab and click "Backup/Erase Settings." A popup informs that a backup is displayed and asks for confirmation to delete the settings.
3. Click OK, then reload PassLok.
At this point, PassLok will take whatever Key the user wishes to provide. If the Key is different from the previous one, however, items stored in the local directory will fail to function.

Since this issue is referenced by a more recent issue, I'm keeping it open until that one is resolved.
