### ISSUE TITLE
General Directory accesses online content without warning user

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#14]
In clicking around (Main -> Edit -> General Directory), you end up with a page that is using an iframe to embed an online resource.

This leaks metadata, such as how often a PassLok user is connecting to the General Directory. A user trying to maintain privacy might not want that kind of signalling. They might have downloaded the web app, or installed the browser extension, hoping that they won't be able to do any action that would leak activity data. 

A visual indication should be made to make it very clear to the user that they are about to do something that will reduce their online privacy.

**Comment by fruiz500** [comment]
The General Directory is simply a website where users can post their Locks, which are not secret material. Opening the General Directory page would leak that the user wants to get another user's Lock, or wants to post his/her own. This is the same thing that happens when a PGP user connects to a key server, except that the PassLok code itself never sees the connection.

Still, I agree a warning to the user is in order. It will be added as a tooltip for the General Directory button and in the Learn Mode confirmation. Same thing with the other iframe contained within PassLok, which is the Chat window.

**Comment by fruiz500** [comment]
Version 2.1.03 adds the features in the post above. This involved changing the behavior of the Chat button, which previously did not show any warning if the chat invitation contained no additional data. Now the additional data is shown if present, plus a warning that the user is about to connect to servers, leaking metadata.
