### ISSUE TITLE
Unable to enter Lock of different user to Lock message

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#2]
I have downloaded the latest version of PassLok.

Using both Firefox (35.0.1) and Chromium (38.0.2125.122 (290379)), I tried the following:
1. Loaded PassLok app
2. Entered in passphrase & "salt" token (?)
3. Clicked on "Main" tab
4. Clicked on 'Edit'
5. Entered name and PassLok Lock of intended recipient
6. Hit 'Save', nothing happens
7. Click 'Done'. Returning to 'Main' tab, recipient does not appear.

This is a big issue, since this means that I cannot Lock any messages.

**Comment by fruiz500** [comment]
Thanks, Tomer,

From your description, it seems that the code is crashing in step 6, since
it should display a confirmation message saying that the Lock has been
saved. But I cannot reproduce the problem. Would you be able to do it again
and tell me if the javascript console says anything?

Thanks!

On Thu, Jan 29, 2015 at 1:02 PM, Tomer Altman notifications@github.com
wrote:

> I have downloaded the latest version of PassLok.
> 
> Using both Firefox (35.0.1) and Chromium (38.0.2125.122 (290379)), I tried
> the following:
> 1. Loaded PassLok app
> 2. Entered in passphrase & "salt" token (?)
> 3. Clicked on "Main" tab
> 4. Clicked on 'Edit'
> 5. Entered name and PassLok Lock of intended recipient
> 6. Hit 'Save', nothing happens
> 7. Click 'Done'. Returning to 'Main' tab, recipient does not appear.
> 
> This is a big issue, since this means that I cannot Lock any messages.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/fruiz500/passlok/issues/2.

## 

Francisco Ruiz
Associate Professor
MMAE department
Illinois Institute of Technology

PL21ezLok=1iw+0_y5xyh_66nby_u12x1_hmdw8_iioou_6yhud_a8/i9_jd4fj_fvv6i_swkrn_u773t_jb7yr_+d9nn_/b4h6_880py_vtf4L_o4zwr_6207u_v/bdd=354ad_7836e_52c1a_2cae9=PL21ezLok
https://www.youtube.com/watch?v=A0LtNkM2RSs https://www.youtube.com

get the PassLok privacy app at: https://passlok.com http://passlok.com

**Comment by taltman** [comment]
I have not been able to reproduce this easily. It might have been a transient "bad state". I will try to find a way to reproduce. I'll close the issue for now.
