### ISSUE TITLE
Idiosyncratic format for key & message formats

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#5]
The key and ciphertext format should follow the appropriate RFCs. This will make it compatible with other programs, such as PGP/GPG, Mailvelope, Enigmail, etc. 

In short, it's not clear how much improved this format is, and it breaks with Internet cryptography standards.

See recent releases of "modern" GPG for examples of what standards-compliant ECC keys and ECC ciphertext looks like.

**Comment by fruiz500** [comment]
I haven't given much thought to making PassLok output compliant with standards, especially those based on PGP/GPG. I've rather tried to optimize it so it is compact, efficient, and resistant to corruption (which PGP/GPG is not).

Perhaps we can discuss what could be gained by making it compliant. Is there a document where I could read up on this?

Thanks!

**Comment by fruiz500** [comment]
I'm looking at the proposed standard for ECC-DH in OpenPGP, which presumably is already standards-compliant, found at https://tools.ietf.org/html/rfc6637, and in section 8 I find the following concerning material that MUST be included as part of the ciphertext:

"20 octets representing a recipient encryption subkey or a master
      key fingerprint, identifying the key material that is needed for
      the decryption"

This leaks the recipient's identity and would be flatly contrary to the design principles underlying PassLok. Since this would never be done in PassLok, I guess it's not going to follow this standard for the time being. I would appreciate it if people could point to a standard that does not contain this rather huge flaw.

**Comment by taltman** [comment]
I think you are in good company in not being scrupulous about complete compliance for all accepted and draft OpenPGP RFCs.
Allow me to be more clear. What I'm proposing is that instead of the current formatting for keys and messages, the formatting can be like this:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PassLok v0.9.7 
Comment: For info see http://passlok.weebly.com/get-passlok.html

[...]
-----END PGP PUBLIC KEY BLOCK-----

This is more like what other programs are already used to parsing with OpenPGP, some of which can support the NIST curve that PassLok uses (IIRC).

Alternatively, can you explain the design decisions behind the current formatting?

**Comment by fruiz500** [comment]
PassLok currently uses a simplified format that goes like this:
- Initial tag so the user (and maybe a parsing program) knows the nature and version of what follows. E.g.: PL21ezlok=  .Which can be read as "PassLok v2.1 ezLok", plus a "=" separator.
- Base64 content string, which has its own internal structure for each kind of output (this is explained in the technical document).
- Hexadecimal error correction string (optional), of the form: =1234567890abcdef1234= . Here the "=" signs are also used as separators.
- Final tag: =PL21ezlok
  All of it without line feeds, which would be different depending on the encoding used and do lead to  frustration when trying to use PGP items.

The idea is to make the overall item as compact as possible, which PGP items are not. I'd like users to be able to dictate their Locks (public keys) over the phone, if possible. Since currently there is only a need to point out the version of PassLok that generated the output plus the type of item, I don't seed a need for more complex headers and footers.

But then, there is parsing by third-party programs. . . . Is there any program out there trying to use PassLok-generated items? Since PassLok is very different from PGP/GPG in many ways, won't formatting its output similarly lead to user confusion and frustration?

**Comment by fruiz500** [comment]
There being no further discussion, I'm closing this issue.
