### ISSUE TITLE
Message should not use the term 'anonymous'

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#6]
The email message says 'Anonymous message'. This is incorrect. PassLok does not provide guarantees of anonymity, just message secrecy and message integrity.

**Comment by fruiz500** [comment]
The word "Anonymous" is used to designate the encryption mode used, so a recipient who is not necessarily versed in cryptography knows that it is no use trying to identify the sender strictly from the ciphertext.

Perhaps the help section of PassLok could clarify what "anonymous" (for lack of a better word) means in PassLok. Currently it is used to designate an encryption algorithm, not very different from ElGamal, where the message key (actually, the key used to encrypt the real message key) is the DH combination of the recipient's private key and an ephemeral public key, based on a random private key, that is included as part of the encrypted output. I believe it is truly anonymous since nobody can deduce who the sender might be by just looking at the encrypted output, but maybe I'm using the term "anonymous" incorrectly.

A bigger problem would be the use of the term "Signed" to refer to an encryption algorithm where the DH combination is made with the recipient's public key and the sender's private key. It is not signed in the strict sense since no digital signature algorithm is involved, but rather in a user experience sort of sense: the recipient must supply the sender's public key, and only if this public key is correct does decryption succeed.

There are other items in PassLok that are named in a rather loose way, and those are usually capitalized: "Key" instead of "private key", "Lock" instead of "public key", and so on. I believe that using precise cryptography language would confuse most users, probably leading them to commit serious errors as has been abundantly documented with PGP and its derivatives. Thus PassLok uses simplified terminology on its interface, aimed as common users.

**Comment by taltman** [comment]
Thanks for the clarification.
This makes me nervous for a few reasons:
1 It sounds like you are describing an encryption algorithm of your own creation ("an encryption algorithm, not very different from ElGamal"). Is that correct? Or has this algorithm been vetted by peer-review?
2 As a novice user, I had no idea that my message was being sent in this 'Anonymous' mode. 
3 I don't think that the word 'Anonymous' really captures what is happening here, and might mislead users.

I'm finding your description of the protocol a bit confusing. For example, you use the term "recipient's private key" in describing the derivation of the message encryption key. How would the sender, using the PassLok App, have access to the recipient's private key, unless there's a multi-pass protocol happening between the sender and the recipient, and that's where the DH comes in to play? I think an explicit description of the protocol would be helpful.

I think for users who are non-technical, but at least aware of why they might want to protect their privacy online, will think of the term 'anonymous' in the same way that when they use Tor (correctly), their web browsing is anonymous. Or when using Mixminion, for pseudonymous communication. What you are describing is really more like deniable encryption, like in OTR:
https://en.wikipedia.org/wiki/Repudiation_%28cryptography%29

I totally agree with you about the need to focus on the user experience, and not having technically-precise language in the user-facing UI and documentation. But I definitely think you need this precision in developer / crytographer-facing documentation. I think it merely needs tweaking in terms of the clearest terminology & explanation for end-users, and the corresponding UI elements to make it clear when it is enabled, and when it is not, and how it helps the user.

**Comment by fruiz500** [comment]
This is what I can easily do:
1. Define "Anonymous" mode more precisely in the Help section. This way users who want to avoid being tracked will know that the term is not meant in that sense.  I will do the same with other possibly controversial terms.
2. Use the specialized meaning of the term in the technical document, capitalizing any word used in non-standard ways. This is done already, but likely it is not done with complete consistence. Thanks for pointing this out.

 Incidentally, in common English "anonymous" means exactly the same as "Anonymous" in PassLok, not what it means in Tor and similar packages. It is the crypto jargon that is using terms in non-standard and confusing ways.

**Comment by taltman** [comment]
Can you address my question about documentation of the 'Anonymous' mode? I see further mention in the technical docs, but no citations. Did you create this?

**Comment by taltman** [comment]
I'm not sure I follow regarding the usage of the term 'anonymous'. How is using Tor not anonymous in the technical meaning of the word (without name)? My fear with using that term with mail is that non-technical users might not understand that the encrypted payload is anonymous in the sense that there's no meaningful identifier associated with it, but the overall email is definitely leaking plenty of meta-data. I think it is misleading.

**Comment by fruiz500** [comment]
Can you suggest a better term for a non-technical user to understand that Anonymous (capitalized) means in the current form of PassLok? That is: a message whose authorship cannot be determined.

Thanks!

**Comment by taltman** [comment]
How about "Ambiguous" or "Deniable"?

In OTR repudiation, one cannot determine which party in the chat contributed which message. Since I don't know if PassLok is using the same method as OTR, I don't know if the same property holds. Is the authorship not known from the set of participants, or a different (larger) set?

**Comment by fruiz500** [comment]
I'm going to run a usability testing this summer, where one of the main questions to be answered is the use of certain terms such as "Anonymous." Which is more confusing to actual users: "Anonymous" or "Deniable" (or "Ambiguous", or whatever). Hopefully the study will solve this issue. I'll go with whatever is less confusing to average users.
